version: '3'

services:
  zabbix-server:
    image: plocek/zabbix-python
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./externalscripts:/usr/lib/zabbix/externalscripts
      - ./alertscripts:/usr/lib/zabbix/alertscripts
    depends_on:
      - mysql
    env_file: .env
    environment:
      - DB_SERVER_HOST=mysql
      - ZBX_CACHESIZE=100M
      - ZBX_VALUECACHESIZE=100M
      - ZBX_TRENDCACHESIZE=30M
      - ZBX_HISTORYCACHESIZE=30M
      - ZBX_HISTORYINDEXCACHESIZE=20M
      - ZBX_STARTPOLLERS=50
      - ZBX_IPMIPOLLERS=3
      - ZBX_DEBUGLEVEL=0

  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - ./datadir:/var/lib/mysql
    env_file: .env

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - zabbix-server:zabbix-server
    depends_on:
      - mysql
      - zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./ssl:/etc/ssl/nginx
      - ./nginx.conf:/etc/zabbix/nginx.conf:ro
    user: root
    env_file: .env
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql
      - TZ=Europe/Vienna

  smtp:
    image: namshi/smtp
    restart: always
    expose:
      - "25"

networks:
  default:
    external:
      name: www-network
